In [1]:
import numpy as np

In [2]:
def calculate_total_distance(sequence, distance_matrix):
    total_distance = 0
    for i in range(len(sequence) - 1):
        total_distance += distance_matrix[sequence[i]][sequence[i + 1]]
    total_distance += distance_matrix[sequence[-1]][sequence[0]]  # Return to the starting city
    return total_distance

In [3]:

def initialize_population(num_chromosomes, num_cities):
    population = []
    for _ in range(num_chromosomes):
        sequence = np.random.permutation(num_cities)
        population.append(sequence)
    return population


In [4]:

def roulette_wheel_selection(population, fitness_values):
    probabilities = fitness_values / sum(fitness_values)
    selected_indices = np.random.choice(len(population), size=len(population), p=probabilities)
    return [population[i] for i in selected_indices]



In [5]:
def crossover(parent1, parent2):
    crossover_point = np.random.randint(1, len(parent1))
    child1 = np.concatenate((parent1[:crossover_point], [city for city in parent2 if city not in parent1[:crossover_point]]))
    child2 = np.concatenate((parent2[:crossover_point], [city for city in parent1 if city not in parent2[:crossover_point]]))
    return child1, child2



In [6]:

def genetic_algorithm(distance_matrix, num_iterations, num_chromosomes):
    num_cities = len(distance_matrix)
    population = initialize_population(num_chromosomes, num_cities)

    for iteration in range(num_iterations):
        fitness_values = [1 / calculate_total_distance(chromosome, distance_matrix) for chromosome in population]

        # Elitism: Select the best chromosome
        best_index = np.argmax(fitness_values)
        next_population = [population[best_index]]

        # Roulette-wheel selection and crossover
        selected_population = roulette_wheel_selection(population, fitness_values)
        for i in range(0, len(selected_population) - 1, 2):
            parent1, parent2 = selected_population[i], selected_population[i + 1]
            child1, child2 = crossover(parent1, parent2)
            next_population.extend([child1, child2])

        population = next_population

    # Select the best solution
    best_solution_index = np.argmax([calculate_total_distance(chromosome, distance_matrix) for chromosome in population])
    best_solution = population[best_solution_index]

    return best_solution




In [7]:
# Example usage:
num_cities = 15
num_iterations = 20
num_chromosomes = 15

# Generate a random distance matrix for demonstration purposes
distance_matrix = np.random.randint(1, 100, size=(num_cities, num_cities))
print(distance_matrix)

best_solution = genetic_algorithm(distance_matrix, num_iterations, num_chromosomes)
print("Best sequence of cities:", best_solution)
print("Total distance:", calculate_total_distance(best_solution, distance_matrix))

[[41 69 76 40 33 28 18 77 92 68 33 68 82  2 54]
 [69 58 71 42 59 32 38 72 38 78 62 13 23 22 24]
 [81 84 56 67  3 36 44 17 55  4 57 98 45 87 43]
 [17 65 18 48 43 80 98 83 31 51  8 50  3 49 38]
 [78 55  7 69 11  7 69  8 42 91 24 35 70 33  9]
 [20 41 39 98 43 59  2 90 44 88 63  5 83 91 80]
 [61 22 32 93 65 24 10 33 59 68 42 69 13 76 14]
 [50 99 40 91 11 51 73 77 16 96 62 43  3 37 58]
 [38 65 67 83 76 34 65 11 60 18 55  1 59 88 38]
 [45 56 72 33 55 55 60 74 19 76 76 45  6 99 87]
 [71 93 41 99 91 23 39  1 37 54 14 39 42 88 28]
 [80 52 76 58 55 50 26 71 90 81 48 56 84 25 11]
 [41 75 95 60 17  6 65 43 11 13 69 69 85 72 49]
 [25 47 14 56 90 77 34 68 45  6 57 25 98 84  7]
 [68 99 43 94 91 51 25 65 72 32 53 14 84 84 60]]
Best sequence of cities: [14 13  0  4  5 11  3  6  2 10 12  1  7  8  9]
Total distance: 709
