In [1]:
import numpy as np

In [2]:
def calculate_total_distance(sequence, distance_matrix):
    total_distance = 0
    for i in range(len(sequence) - 1):
        total_distance += distance_matrix[sequence[i]][sequence[i + 1]]
    total_distance += distance_matrix[sequence[-1]][sequence[0]]  # Return to the starting city
    return total_distance

In [3]:

def initialize_population(num_chromosomes, num_cities):
    population = []
    for _ in range(num_chromosomes):
        sequence = np.random.permutation(num_cities)
        population.append(sequence)
    return population


In [4]:

def roulette_wheel_selection(population, fitness_values):
    probabilities = fitness_values / sum(fitness_values)
    selected_indices = np.random.choice(len(population), size=len(population), p=probabilities)
    return [population[i] for i in selected_indices]



In [5]:
def crossover(parent1, parent2):
    crossover_point = np.random.randint(1, len(parent1))
    child1 = np.concatenate((parent1[:crossover_point], [city for city in parent2 if city not in parent1[:crossover_point]]))
    child2 = np.concatenate((parent2[:crossover_point], [city for city in parent1 if city not in parent2[:crossover_point]]))
    return child1, child2



In [6]:

def genetic_algorithm(distance_matrix, num_iterations, num_chromosomes):
    num_cities = len(distance_matrix)
    population = initialize_population(num_chromosomes, num_cities)

    for iteration in range(num_iterations):
        fitness_values = [1 / (1 + calculate_total_distance(chromosome, distance_matrix)) for chromosome in population]


        # Elitism: Select the best chromosome
        best_index = np.argmax(fitness_values)
        next_population = [population[best_index]]

        # Roulette-wheel selection and crossover
        selected_population = roulette_wheel_selection(population, fitness_values)
        for i in range(0, len(selected_population) - 1, 2):
            parent1, parent2 = selected_population[i], selected_population[i + 1]
            child1, child2 = crossover(parent1, parent2)
            next_population.extend([child1, child2])

        population = next_population

    # Select the best solution
    best_solution_index = np.argmax([calculate_total_distance(chromosome, distance_matrix) for chromosome in population])
    best_solution = population[best_solution_index]

    return best_solution




In [7]:
# Example usage:
num_cities = 15
num_iterations = 20
num_chromosomes = 15

# Generate a random distance matrix for demonstration purposes
distance_matrix = np.random.randint(1, 100, size=(num_cities, num_cities))
np.fill_diagonal(distance_matrix, 0)  # Set diagonal elements to 0

print("Random Distance Matrix:")
print(distance_matrix)

best_solution = genetic_algorithm(distance_matrix, num_iterations, num_chromosomes)
print("Best sequence of cities:", best_solution)
print("Total distance:", calculate_total_distance(best_solution, distance_matrix))


Random Distance Matrix:
[[ 0 93 41 70 63 63 56 86 43 38 10 92 25 85  9]
 [77  0 31 95 10 37 90 74 26 96 62 76 58 29 70]
 [51 18  0 23 58 96  6 13 82 51 96 52 12 27 82]
 [96 43 65  0 91 17 19 37 19 18 41 61  6 66 79]
 [37 63 38 97  0 12 58 30 12 96 23 83 95 58 80]
 [11 95 58 51 11  0 96 65 49 17 53 76 37 11 74]
 [64 22 82 70 64 29  0 53 65 90 21 80 28 57 35]
 [12 26 53 99 43 50 79  0 66 76 37 19 40 42 27]
 [70 20 70 69 49 34 40 10  0 36 69 70 83 96 68]
 [88 56  6 23 77 62 46 34  6  0 52 46 12 72 62]
 [90 41 19 98 74 68 23  7 32 32  0 10 99 74 50]
 [26 12 31  7 45  9 10 23 37 25 80  0 56 64 58]
 [22 18 41 91 75  6 84 80 65 17  5 43  0 53 75]
 [91 98 22 34 44 67 73  2 71 38 75 33 18  0 98]
 [99 33 16 53 24 43 70 87  3 26 28 67 53 68  0]]
Best sequence of cities: [ 5  9  3 10  7 13  2 11 12  6 14  8  0  1  4]
Total distance: 567
