In [1]:
import numpy as np

In [2]:
def calculate_total_distance(sequence, distance_matrix):
    total_distance = 0
    for i in range(len(sequence) - 1):
        total_distance += distance_matrix[sequence[i]][sequence[i + 1]]
    total_distance += distance_matrix[sequence[-1]][sequence[0]]  # Return to the starting city
    return total_distance

In [3]:
def initialize_population(num_chromosomes, num_cities):
    population = []
    for _ in range(num_chromosomes):
        sequence = np.random.permutation(num_cities - 1) + 1  
        sequence = np.insert(sequence, 0, 0)  
        population.append(sequence)
    return population



In [4]:


def roulette_wheel_selection(population, fitness_values):
    fitness_values = np.array(fitness_values)  
    probabilities = fitness_values / sum(fitness_values)
    selected_indices = np.random.choice(len(population), size=len(population), p=probabilities)
    return [population[i] for i in selected_indices]


In [5]:
def crossover(parent1, parent2):
    crossover_point = np.random.randint(1, len(parent1))
    child1 = np.concatenate((parent1[:crossover_point], [city for city in parent2 if city not in parent1[:crossover_point]]))
    child2 = np.concatenate((parent2[:crossover_point], [city for city in parent1 if city not in parent2[:crossover_point]]))
    return child1, child2



In [6]:

def genetic_algorithm(distance_matrix, num_iterations, num_chromosomes):
    num_cities = len(distance_matrix)
    population = initialize_population(num_chromosomes, num_cities)

    for iteration in range(num_iterations):
        fitness_values = [1 / (1 + calculate_total_distance(chromosome, distance_matrix)) for chromosome in population]


        # Elitism: Select the best chromosome
        best_index = np.argmax(fitness_values)
        next_population = [population[best_index]]

        # Roulette-wheel selection and crossover
        selected_population = roulette_wheel_selection(population, fitness_values)
        for i in range(0, len(selected_population) - 1, 2):
            parent1, parent2 = selected_population[i], selected_population[i + 1]
            child1, child2 = crossover(parent1, parent2)
            next_population.extend([child1, child2])

        population = next_population

    # Select the best solution
    best_solution_index = np.argmin([calculate_total_distance(chromosome, distance_matrix) for chromosome in population])
    best_solution = population[best_solution_index]

    return best_solution




In [7]:
# Example usage:
num_cities = 15
num_iterations = 20
num_chromosomes = 15
#you can check with different matrices.Note that edges are directed in our case
distance_matrix = np.random.randint(1, 100, size=(num_cities, num_cities))
np.fill_diagonal(distance_matrix, 0)

print("Distance Matrix:")
print(distance_matrix)

best_solution = genetic_algorithm(distance_matrix, num_iterations, num_chromosomes)
print("Best sequence of cities:", best_solution)
print("Total distance:", calculate_total_distance(best_solution, distance_matrix))


Distance Matrix:
[[ 0 55 47 15 82 39 59 62 50 31 63  9 81 74  4]
 [10  0 16 23 59 28 76 19 38  3  5  7 36 95 51]
 [85 40  0 27 62 79 23 25 31 82 58 35 43 73 96]
 [15 58 94  0 30 58 80 74 92 18 74 84 50  5 15]
 [95  9 25 42  0 70 96 11 66 66 83 60 42 35 12]
 [17 42 85 12 52  0 69 72 79  5 20 85 76 61 21]
 [50 88  5 80 37 33  0 88 97 47 96  1 55 61 76]
 [96 84 84 43 34  6 20  0 62 78 20 90 38 66 93]
 [33 42 73  2 39 81 13 73  0 15 10 86 49 89 72]
 [83 37 55 38 42 62 20 98 11  0 63 70 51 70 57]
 [78 92 61  8 33  6 64 41 89 42  0 23 31 70 92]
 [44  6 96 55  3 34  3 89 19 47 32  0 15 15  8]
 [50 56 42 58 62 96 90 90 44 54 38 53  0 15 49]
 [16 61 54 90 10 67 91 31 38 40 35 76 56  0 22]
 [67 89 57 20 80 68 74 65 41 67 78 71 16  9  0]]
Best sequence of cities: [ 0  5  9  8 10  3 13 14  2  6 11 12  7  4  1]
Total distance: 339
